
global:
  no_sleep: true
  #log_file: logs/program_output.log
  log_file: logs/program_output.{{ .Now }}.log
  etat_file : etat_backup.txt

tasks:
  -
    name: "commande 1"
    run: cmd /C echo coucou
    enable: true
  -
    name: "commande 2"
    run: cmd /C echo suite
    enable: true
  -
    name: "commande 3"
    run: cmd /C dir
    enable: true
    encoding: Windows1252
    #encoding: ISO88591
  -
    name: "commande 4"
    commands: [ "cmd", "-/C", "echo", "La date est {{ .Now }}"]
    enable: true


